services:
  yoink:
    image: jbritain/yoink:latest
    container_name: yoink
    network-mode: host
    restart: unless-stopped
    environment:
      - NAME=YOUR_SERVER_NAME # appears at the top of the webpage
      - MAC=00:11:22:33:44:55 # the target's MAC address
      - IP=192.168.1.123 # the target's IP address
      - PORT=8080 # port to run on